FROM rust:1.84.1-bookworm AS builder
WORKDIR /app

COPY Cargo.toml Cargo.lock /app/
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release

COPY . /app/
RUN touch src/main.rs
RUN cargo build --release

FROM gcr.io/distroless/cc-debian12
COPY --from=builder /app/target/release/axum-lambda-sample /app/axum-lambda-sample
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.9.0 /lambda-adapter /opt/extensions/lambda-adapter
CMD ["/app/axum-lambda-sample"]
